steps:
- name: maven:3.6.0-jdk-11-slim
  entrypoint: mvn
  args: ['--initialize', '--file', 'Engine/pom.xml' ] 
- name: maven:3.6.0-jdk-11-slim
  entrypoint: mvn
  args: ['--install', '--file', 'Engine/pom.xml' ]  
- name: 'ubuntu'
  args: ['chmod', '-R', '755', './' ]
- name: 'ubuntu'
  args: ['./Run.command', '-run', '-project_location', 'Projects/ING-Public-Web', '-release', 'Release1', '-testset', 'Set1' ]      
